Features
student-to-dev/Omex-landing-page pull request #58
Opened 2022-10-27 17:06 UTC by sauliusss

jauciu uz tokiu dalykus gausiu bana, bet gal dabar tures normaliau veikt

2022-10-28 00:19 UTC, eyyMinda requested changes

2022-10-28 00:19 UTC, eyyMinda commented on css/components/features.css
> +  .container .row {
.container .row = no go

2022-10-28 00:19 UTC, eyyMinda commented on css/pages/home.css
> +<<<<<<< Updated upstream
~~

2022-10-28 00:19 UTC, eyyMinda commented on css/pages/home.css
> +=======
~~

2022-10-28 00:19 UTC, eyyMinda commented on index.html
> +      <!-- Landing -->
Ištrinta viskas apart features

2022-10-28 00:19 UTC, eyyMinda commented on css/pages/home.css
> +>>>>>>> Stashed changes
~~

2022-10-28 08:06 UTC, sauliusss reviewed
lyg ir patvarkiau?

2022-11-02 13:55 UTC, agnekauk commented on index.html
> +              <div class="features_btn">Check all features</div>
Čia turbūt trūksta .btn klasės, nes užhoverinus neatsiranda arrow animacija.

2022-11-03 20:12 UTC, sauliusss commented on index.html
> +              <div class="features_btn">Check all features</div>
Patvarkyta

2022-11-04 16:32 UTC, sauliusss reviewed
patvarkyta

2022-11-04 20:33 UTC, eyyMinda approved these changes

2022-11-04 20:33 UTC, merged